### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by guist** [manycore-research/PlankAssembly#4]
Hello,

I have an additional question regarding the way of preparing the data for inference.

When I run the testing script using the `configs/train.yaml`, I get the following error:

> File "/home/guist/PlankAssembly-atlas/plankassembly/data.py", line 246, in __getitem__
>     svgs = info['svgs']
> KeyError: 'svgs'

I checked the json file and there is indeed no 'svgs' field so I was wondering how to modify the file so that it works. More generally, how should I prepare my custom images so that I can apply your model on them?

Thanks a lot for the answer.

Best regards,
Guillaume

**Comment by bertjiazheng** [comment]
Hi,

The PlankAssembly dataset provides shape programs for the 3D model. To train or test the model, you should first prepare the data following [here](https://github.com/manycore-research/PlankAssembly?tab=readme-ov-file#dataset).

The input data should include three orthographic line drawings. Refer to the line drawing renderings [scripts](https://github.com/manycore-research/PlankAssembly/blob/main/dataset/render_complete_svg.py#L25) for more information.

Best,
Jia

**Comment by guist** [comment]
Hi,

Thanks for your explanations, I could prepare the data and run the full testing script.

Best,
Guillaume
