### ISSUE TITLE
系统问题

### ISSUE THREAD

**Issue by genius37** [manycore-research/PlankAssembly#6]
作者你好。想请问下您是在什么系统下跑的？因为我在训练得那一步出了点问题

**Comment by bertjiazheng** [comment]
我们使用Ubuntu18.04系统，请参考[README](https://github.com/manycore-research/PlankAssembly?tab=readme-ov-file#setup)来配置你的环境。

**Comment by genius37** [comment]
您好，谢谢你的回答，我还想问一下您当时训练用了多长时间，我看您是用四个gpu跑的，我如果只用一个会不会工程量太大了呀

**Comment by bertjiazheng** [comment]
我们没有尝试使用单张卡训练，所以不能保证单张卡能够复现论文的结果。作为参考，虽然我们所有的模型都训练了1000个epochs，但是大概在500个epochs模型就开始有收敛的表现。

**Comment by genius37** [comment]
好的，谢谢，您给的才考非常有价值！

**Comment by genius37** [comment]
> 我们没有尝试使用单张卡训练，所以不能保证单张卡能够复现论文的结果。作为参考，虽然我们所有的模型都训练了1000个epochs，但是大概在500个epochs模型就开始有收敛的表现。

好的，谢谢!您的参考很有价值
