### ISSUE TITLE
use SVG files as input 

### ISSUE THREAD

**Issue by SanketDhuri** [manycore-research/PlankAssembly#7]
I aim to input SVG files representing the top, bottom, and side orthographic projections of an object. I want to transform these SVG files into a data format suitable for model input data, to reconstruct 3d model

can you give me code reference to do so

**Comment by bertjiazheng** [comment]
Please refer to [parse_info.py](https://github.com/manycore-research/PlankAssembly/blob/main/dataset/prepare_info.py) to convert the SVGs into the desired format.

**Comment by SanketDhuri** [comment]
and how to create this  `infos['planks']` and `infos['attach'] ` data for this line of code `coords = np.array(infos['planks']) / args.scale` since this `coords` and `attach` data is needed in json file

considering this 'f', 't', 's' view are new svg images

**Comment by bertjiazheng** [comment]
`planks` and `attach` are the expected outputs. You may ignore them if you do not have the ground truth. However, you need to modify the dataset to exclude ground truth during inference.

**Comment by SanketDhuri** [comment]
> `planks` and `attach` are the expected outputs. You may ignore them if you do not have the ground truth. However, you need to modify the dataset to exclude ground truth during inference.

thanks @bertjiazheng it worked

**Comment by thanhdat77** [comment]
HI @bertjiazheng,
Thanks for your amazing work, i just wonder if i have the step(or stl) file can i change form it to your json format, and i already generate 3 side of svg image, 
Best regards,

**Comment by bertjiazheng** [comment]
> HI [@bertjiazheng](https://github.com/bertjiazheng), Thanks for your amazing work, i just wonder if i have the step(or stl) file can i change form it to your json format, and i already generate 3 side of svg image, Best regards,

Refer to https://github.com/manycore-research/PlankAssembly/issues/11#issuecomment-2690610875
