### ISSUE TITLE
Reconstructing 3d objects with curves 

### ISSUE THREAD

**Issue by SanketDhuri** [manycore-research/PlankAssembly#8]
The current model performs fine with objects that have distinct edges or are composed of square and rectangular shapes. Can it be adapted to process data for images that contain curves, as shown in the SVG and 3D model below?

Additionally, can the bellow SVG be segmented into separate views—front, top, and side—to input into the model?

![92552_38c9173a_0000](https://github.com/manycore-research/PlankAssembly/assets/144204836/7c7a0406-c899-4751-a0b9-9ec20df4e440)
![92552_38c9173a_0000](https://github.com/manycore-research/PlankAssembly/assets/144204836/5573adab-8b83-4224-a728-1ea3911b9403)

**Comment by bertjiazheng** [comment]
To extend the shape beyond cabinet furniture, you should consider (a) how to encode curved lines in the input sequence, and (b) how to extend the DSL to include complex shapes.

Separating the input views is not within the scope of this project. We assumed that the views have already been separated in this paper.
